modLoader="javafml"
loaderVersion="[39.0.57,)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/AdvancedGolems/issues"
[[mods]]
modId="advancedgolems"
version="${version}"
displayName="Advanced Golems"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-golems"
logoFile="icon.png"
authors="Flemmli97"
description='''Summon small golems that help defend your base'''
[[dependencies.advancedgolems]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="tenshilib"
mandatory=true
versionRange="[1.18.1-1.5.0,)"
ordering="NONE"
side="BOTH"