modLoader="javafml"
loaderVersion="[${loader_version},)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/AdvancedGolems/issues"
[[mods]]
modId="advancedgolems"
version="${version}"
displayName="Advanced Golems"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-golems"
logoFile="icon.png"
authors="Flemmli97"
description='''Summon small golems that help defend your base'''
[[dependencies.advancedgolems]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="tenshilib"
mandatory=true
versionRange="[${tenshilib_version},)"
ordering="NONE"
side="BOTH"
