modLoader="javafml"
loaderVersion="[45,)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/AdvancedGolems/issues"
[[mods]]
modId="advancedgolems"
version="${version}"
displayName="Advanced Golems"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-golems"
logoFile="icon.png"
authors="Flemmli97"
description='''Summon small golems that help defend your base'''
[[dependencies.advancedgolems]]
modId="minecraft"
mandatory=true
versionRange="[1.19.4,)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="forge"
mandatory=true
versionRange="[45.0.22,)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="tenshilib"
mandatory=true
versionRange="[1.19.4-1.6.15,)"
ordering="NONE"
side="BOTH"
