apply from: "https://raw.githubusercontent.com/Flemmli97/GradleScripts/arch-loom-v2/fabric.gradle"

ext {
    mod_meta.tenshilib_version = tenshilib_version
}

repositories {
    maven { url 'https://maven.nucleoid.xyz' }
}

dependencies {
    modImplementation "io.github.flemmli97:tenshilib:${tenshilib_version}-fabric"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api}"

    modImplementation "${polymer}"
    modImplementation "${translation_api}"

    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${project.minecraft_version}:${project.sbl_version}"
}

shadowJar {
    exclude "**/recipes/**_alt.json", "**/advancements/**/**_alt.json"
}