plugins {
    id 'io.github.flemmli97.multiloader.platform-fabric'
}

loom {
    runs {
        client {
            vmArgs "-XX:+AllowEnhancedClassRedefinition"
        }
    }
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
    mod_meta.forge_config_api = forge_config_api
    mod_meta.sbl_version = sbl_version
}

repositories {
    maven {
        url = 'https://maven.nucleoid.xyz'
    }
}

dependencies {
    modImplementation "io.github.flemmli97:tenshilib:${tenshilib_version}-fabric"
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api}"

    modImplementation "${polymer}"
    modImplementation "${translation_api}"

    modImplementation "net.tslat.smartbrainlib:SmartBrainLib-fabric-${project.minecraft_version}:${project.sbl_version}"
}