plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
}

dependencies {
    implementation "io.github.flemmli97:tenshilib:${tenshilib_version}-common"
    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:${forge_config_api}"
    implementation "net.tslat.smartbrainlib:SmartBrainLib-common-${project.minecraft_version}:${project.sbl_version}"
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
    copy {
        from project(":common").file("src/generated/resources/assets/advancedgolems/lang")
        into "$sourceSets.main.output.resourcesDir/data/advancedgolems/lang"
    }
}