modLoader="javafml"
loaderVersion="[${loader_version},)"
license="ARR"
issueTrackerURL="https://github.com/Flemmli97/AdvancedGolems/issues"
[[mixins]]
config = "advancedgolems.mixins.json"
[[mods]]
modId="advancedgolems"
version="${version}"
displayName="Advanced Golems"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Summon small golems that help defend your base'''
[[dependencies.advancedgolems]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="neoforge"
type="required"
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.advancedgolems]]
modId="tenshilib"
type="required"
versionRange="[${tenshilib_version},)"
ordering="NONE"
side="BOTH"
