plugins {
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            data()
            programArguments.addAll "--all", "--mod", "advancedgolems"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
            programArguments.addAll "--existing", common.file("src/main/resources").absolutePath
        }
    }
}

ext {
    mod_meta.tenshilib_version = tenshilib_version
    mod_meta.sbl_version = sbl_version
}

dependencies {
    implementation "io.github.flemmli97:tenshilib:${tenshilib_version}-neoforge"

    implementation "net.tslat.smartbrainlib:SmartBrainLib-neoforge-${project.minecraft_version}:${project.sbl_version}"

    runtimeOnly "io.github.flemmli97:debugutils:1.21.1-1.0.8-neoforge"
}